import { ThemeProvider } from "@/components/ui/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { ConvexClientProvider } from "@/components/web/providers/convex-client-provider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({ subsets: ["latin"], variable: "--font-dm-sans-sans" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn("h-full font-sans antialiased", dmSans.variable)}
			suppressHydrationWarning
		>
			<body className="flex min-h-full flex-col">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<main className="container mx-auto px-4 md:px-6 lg:px-8">
						<ConvexClientProvider>{children}</ConvexClientProvider>{" "}
					</main>
					<Toaster closeButton />
				</ThemeProvider>
			</body>
		</html>
	);
}
